// Editorial picks. When a candidate matches one of these by TMDb ID, it gets
// boosted in ranking and the note appears as a small badge on the card.

export const CURATED = [
  // ── OSCURO · REFLEXIVO ───────────────────────────────────────────
  { id: 965150,  note: "Charlotte Wells filma el duelo desde el fondo de una pileta. Te parte sin que lo notes." },
  { id: 666277,  note: "Celine Song convierte lo que pudo ser en la película más adulta sobre el amor no elegido." },
  { id: 152601,  note: "Jonze construyó el retrato de soledad más honesto de los 2010s. Phoenix nunca estuvo mejor." },
  { id: 466420,  note: "Scorsese a máxima potencia: codicia, crimen, y la América que borra lo que no quiere ver." },
  { id: 804095,  note: "El Spielberg más personal. El cine que te salva y destruye tu familia al mismo tiempo." },
  { id: 496243,  note: "Sátira social que termina cortando profundo." },
  { id: 491584,  note: "Misterio lento, vacío emocional y rabia contenida." },
  { id: 1018,    note: "Hollywood convertido en sueño roto." },
  { id: 843,     note: "Deseo, silencio y elegancia pura." },
  { id: 1398,    note: "Ciencia ficción espiritual y contemplativa." },
  { id: 68722,   note: "Drama hipnótico sobre vacío, fe y dependencia." },
  { id: 11423,   note: "Policial oscuro con tristeza histórica." },

  // ── OSCURO · TENSO ───────────────────────────────────────────────
  { id: 146233,  note: "Villeneuve en estado puro: thriller moral donde ninguna respuesta llega limpia." },
  { id: 49797,   note: "Kim Jee-woon llevó el thriller de venganza al límite. Obra maestra incómoda." },
  { id: 1422,    note: "Scorsese hizo el mejor thriller americano de los 2000s. Traición, ritmo, adrenalina pura." },
  { id: 949,     note: "Mann inventó la estética del thriller moderno. De Niro y Pacino en el pináculo del género." },
  { id: 395834,  note: "Western tardío que nadie esperaba. Frío, preciso, brutal." },
  { id: 27205,   note: "El blockbuster más inteligente de su era. Arquitectura de sueños que no envejece." },
  { id: 244786,  note: "Chazelle convirtió la ambición en tensión pura. Fletcher, uno de los villanos más reales del cine." },
  { id: 1949,    note: "Obsesión investigativa sin recompensa limpia." },
  { id: 473033,  note: "Ansiedad pura disfrazada de cine criminal." },
  { id: 242582,  note: "Capitalismo, morbo y vacío humano." },
  { id: 273481,  note: "Tensión seca, frontera y moral rota." },

  // ── OSCURO · DEVASTADOR ──────────────────────────────────────────
  { id: 807,     note: "Fincher preguntó qué hay en la caja. Nadie quiere saber la respuesta." },
  { id: 9539,    note: "Laugier en el extremo absoluto. Más allá del torture porn: hay tesis filosófica adentro." },
  { id: 334541,  note: "Dolor humano sin consuelo fácil." },
  { id: 641,     note: "Adicción filmada como caída libre." },
  { id: 25237,   note: "La guerra como trauma absoluto." },
  { id: 12477,   note: "Animación que destruye sin exagerar." },
  { id: 670,     note: "Venganza enfermiza con golpe emocional." },
  { id: 6977,    note: "Fatalismo seco, violento y perfecto." },

  // ── LUZ · ACOMPAÑAMIENTO ─────────────────────────────────────────
  { id: 840430,  note: "Vieja escuela en el mejor sentido: personajes, invierno de Nueva Inglaterra y mucha humanidad." },
  { id: 505600,  note: "Buddy comedy que también es algo. Wilde debutó como directora y anotó directo." },
  { id: 122906,  note: "Curtis hace trampas con el tiempo y uno lo acepta. Warm sin ser empalagosa." },
  { id: 587792,  note: "Toma el loop de Groundhog Day y le agrega nihilismo cómico. Sorprendentemente bien ejecutada." },
  { id: 976893,  note: "Calma, rutina y belleza mínima." },
  { id: 370755,  note: "La vida cotidiana como poema tranquilo." },
  { id: 11830,   note: "Comida, humor y ternura japonesa." },
  { id: 331482,  note: "Cálida, sensible y muy humana." },
  { id: 505192,  note: "Familia elegida con ternura y dolor." },
  { id: 194,     note: "Fantasía cálida sin perder melancolía." },

  // ── LUZ · ADRENALINA ─────────────────────────────────────────────
  { id: 353081,  note: "El pico del cine de acción contemporáneo. Cada set-piece es clase magistral." },
  { id: 546554,  note: "Rian Johnson revivió el whodunit con pura inteligencia. Ritmo, humor y nadie muere aburrido." },
  { id: 515001,  note: "Waititi equilibra nazis y ternura sin caer en ningún precipicio." },
  { id: 603,     note: "Acción cyberpunk con ideas grandes." },
  { id: 76341,   note: "Energía visual en estado puro." },
  { id: 85,      note: "Aventura clásica con ritmo perfecto." },
  { id: 155,     note: "Blockbuster tenso, elegante y cerebral." },
  { id: 137113,  note: "Sci-fi de acción ligera y precisa." },
  { id: 361743,  note: "Blockbuster limpio, físico y efectivo." },

  // ── FRÍO · CONTEMPLATIVO ─────────────────────────────────────────
  { id: 329865,  note: "Arrival reencuadra la sci-fi como tragedia lingüística. Villeneuve más preciso." },
  { id: 503919,  note: "Eggers encerró a dos hombres en un faro y filmó la locura como mito griego." },
  { id: 254320,  note: "Lanthimos construyó una distopía del afecto. Extraña, fría y con más verdad de lo que parece." },
  { id: 374720,  note: "Nolan filmó Dunkerque como sensación física. Relato bélico sin héroes individuales." },
  { id: 593,     note: "Recuerdos, duelo y espacio interior." },
  { id: 81401,   note: "Silencio, viento y agotamiento existencial." },
  { id: 414453,  note: "Arquitectura, pausa y melancolía." },
  { id: 30020,   note: "Minimalismo moral y contemplación pura." },

  // ── CÁLIDO · ROMÁNTICO ───────────────────────────────────────────
  { id: 531428,  note: "Romance contenido, elegante y devastador." },
  { id: 76,      note: "Enamorarse conversando, sin artificio." },
  { id: 80,      note: "Romance adulto con tiempo encima." },
  { id: 38,      note: "Romance roto con imaginación emocional." },
  { id: 284,     note: "Romance clásico con tristeza adulta." },

  // ── RARO · DISCOVER ──────────────────────────────────────────────
  { id: 513434,  note: "Una película de zombies dentro de otra. Ueda es un genio caótico." },
  { id: 220289,  note: "$50k en una noche. Física cuántica como paranoia doméstica perfecta." },
  { id: 431,     note: "Kafkiana, matemática y aterradora. Precursora del cine de escape room." },
  { id: 985,     note: "Pesadilla industrial sin explicación segura." },
  { id: 8327,    note: "Misticismo, exceso y locura visual." },
  { id: 662,     note: "Sci-fi mínima, experimental y eterna." },
  { id: 21484,   note: "Ruptura amorosa como posesión demoníaca." },
  { id: 25623,   note: "Terror pop japonés totalmente desquiciado." },
  { id: 97370,   note: "Alienación fría, sexual y extraña." },
  { id: 492,     note: "Comedia absurda con crisis de identidad." },

  // ── ACCIÓN RETRO ─────────────────────────────────────────────────
  { id: 1103,    note: "Carpenter, synth y nihilismo ochentero." },
  { id: 106,     note: "Acción muscular con instinto de horror." },
  { id: 562,     note: "La plantilla perfecta del action moderno." },
  { id: 5548,    note: "Violencia, sátira y metal ochentero." },
  { id: 218,     note: "Sci-fi sucia, nocturna e implacable." },
  { id: 679,     note: "Acción, terror y músculo narrativo." },
  { id: 6978,    note: "Aventura absurda con energía de culto." },

  // ── TERROR ATMOSFÉRICO ───────────────────────────────────────────
  { id: 493922,  note: "Ari Aster redefinió el horror familiar. Te deja sin herramientas para procesar lo que viste." },
  { id: 310131,  note: "Eggers construyó el miedo de adentro hacia afuera. Folk horror en estado puro." },
  { id: 530385,  note: "Horror diurno en flores amarillas. Lo más perturbador es que el culto tiene lógica interna." },
  { id: 293670,  note: "Folklore coreano, exorcismo y paranoia. Absolutamente impredecible." },
  { id: 27374,   note: "La película de terror más melancólica que existe. Documental falso. Duelo como horror." },
  { id: 575776,  note: "Powell filmó la fe como posesión. Horror que nace de la devoción." },
  { id: 694,     note: "Aislamiento, arquitectura y terror psicológico." },
  { id: 805,     note: "Paranoia doméstica con elegancia diabólica." },
  { id: 36095,   note: "Hipnosis, crimen y miedo invisible." },

  // ── COMEDIA CON ALMA ─────────────────────────────────────────────
  { id: 275,     note: "Humor negro con alma congelada." },
  { id: 120467,  note: "Comedia elegante con melancolía escondida." },
  { id: 121986,  note: "Caótica, honesta y dolorosamente humana." },
  { id: 773,     note: "Indie familiar con corazón genuino." },
  { id: 115,     note: "Absurdo, relajo y filosofía accidental." },
  { id: 8051,    note: "Comedia romántica nerviosa y preciosa." },
  { id: 86829,   note: "Fracaso artístico con humor seco." },

  // ── ANIMACIÓN ADULTA ─────────────────────────────────────────────
  { id: 324857,  note: "Reinventó la animación y el superhéroe en un solo golpe. Estilo, ritmo, corazón." },
  { id: 569094,  note: "Supera al original. La secuencia del Spider-Man 2099 sola vale todo el cine de 2023." },
  { id: 10494,   note: "Identidad, fama y paranoia digital." },
  { id: 9323,    note: "Cyberpunk filosófico y existencial." },
  { id: 128,     note: "Épica ecológica, violenta y madura." },
  { id: 129,     note: "Fantasía total con peso emocional." },
  { id: 149,     note: "Caos urbano, cuerpo y poder." },
  { id: 378064,  note: "Culpa, bullying y redención sensible." },
  { id: 10315,   note: "Wes Anderson en stop motion perfecto." },

  // ── DOCUMENTAL ───────────────────────────────────────────────────
  { id: 682110,  note: "Un hombre aprende de un pulpo durante un año. Suena tonto. Te cambia algo por dentro." },
  { id: 123678,  note: "La realidad más perturbadora que la ficción." },
  { id: 128216,  note: "Memoria familiar y verdad inestable." },
  { id: 501,     note: "Herzog mirando obsesión y naturaleza." },
  { id: 42044,   note: "Monumental, duro e imposible de olvidar." },
  { id: 14275,   note: "Sueños, clase y deporte sin maquillaje." },
  { id: 30017,   note: "Documental, ficción e identidad mezcladas." },
  { id: 26317,   note: "Cine mirando al cine desde el origen." },


  // ── MÁS PICKS (oscuro/luz/calido/frío/clásico) ──────────────────
  { id: 769    , note: "Scorsese filmó el mafioso como pesadilla americana. Tres horas que pasan como una hora." },
  { id: 311    , note: "Leone hizo el adiós más largo del cine. Cuatro horas de melancolía y memoria fragmentada." },
  { id: 510    , note: "Forman convirtió el manicomio en alegoría política. Nicholson nunca volvió a estar mejor." },
  { id: 274    , note: "Demme hizo del thriller psicológico una conversación. Foster y Hopkins en estado puro." },
  { id: 550    , note: "Fincher nos enseñó a odiar nuestros muebles. Ironía masculina antes de que se entendiera." },
  { id: 16     , note: "Von Trier convirtió el musical en martirio. Björk te destruye sin filtro." },
  { id: 24     , note: "Tarantino reescribió la grieta del cine moderno. Amargura, ritmo, charla y muerte." },
  { id: 8587   , note: "Disney peak. Dolor edípico filmado con coros zulúes y un león filosófico." },
  { id: 12     , note: "Pixar al máximo: oceáno, padre roto y un pez con memoria de tres segundos." },
  { id: 78     , note: "Scott pintó Los Ángeles 2019 con humo y neón. Cyberpunk antes del término." },
  { id: 335984 , note: "Villeneuve respetó a Scott y agregó tristeza ambiental. Sequel imposible que existe." },
  { id: 4348   , note: "Wright filmó Austen como tormenta de campo inglés. Knightley nunca tan radiante." },
  { id: 1585   , note: "Donen convirtió el thriller en comedia romántica. Hepburn y Grant casi flirteando con la muerte." },
  { id: 539    , note: "Hitchcock destruyó la lógica narrativa en una ducha. 1960 y todavía marca el reloj del género." },
  { id: 567    , note: "Hitchcock mirando el voyeurismo del cine. Stewart en su silla, todos somos él." },
  { id: 238    , note: "Coppola convirtió la familia mafiosa en Shakespeare moderno. Estructura perfecta." },
  { id: 240    , note: "Coppola hizo la secuela más ambiciosa del cine americano. De Niro joven, Pacino congelándose." },
  { id: 597    , note: "Cameron filmó el desastre como melodrama eficaz. Hate quien quiera, funciona en la sala." },
  { id: 4584   , note: "Jeunet hizo París como cuento de hadas. Tautou inventó un tipo de protagonista." },

  // ── EXTRAS · pool diversity ─────────────────────────────────────
  { id: 637    , note: "Benigni convirtió el horror en cuento. Comedia y tragedia en la misma respiración." },
  { id: 1124   , note: "Aronofsky filmó la matemática como obsesión paranoide. B&N y dolor de cabeza." },
  { id: 629    , note: "Singer escondió el final en plain sight. Spacey antes de cancelarse." },
  { id: 497    , note: "Frears + Cusack: comedia de listas y rupturas como única estructura emocional." },
  { id: 4011   , note: "Burton + Depp: cuento gótico de pueblo americano. Christopher Walken sin cabeza." },
  { id: 1417   , note: "Inside Llewyn Davis. Coens en clave folk. Fracaso artístico filmado con cariño." },
  { id: 1538   , note: "Sicario. Villeneuve. Frontera, narcos, moral en pedazos." },
  { id: 313369 , note: "La La Land. Chazelle. Romance que termina en lo posible no escogido." },
  { id: 157336 , note: "Interstellar. Nolan. Padre, hija, tiempo elástico." },
  { id: 508442 , note: "Soul. Pixar adulta. Jazz y existencialismo de muñeco." },
  { id: 508439 , note: "Onward. Hermanos y duelo paterno animado." },
  { id: 598    , note: "Ciudad de Dios. Meirelles. Río como purgatorio infantil." },
  { id: 426426 , note: "Roma. Cuarón. Memoria personal filmada con grúa." },
  { id: 160068 , note: "El club. Larraín. Iglesia, abuso y silencio chileno." },
  { id: 32     , note: "Gondry rebobinó la memoria del amor. Carrey y Winslet sin caretas." },
  { id: 425    , note: "Polanski. París como laberinto familiar. Repulsión disfrazada de departamento." },
  { id: 508943 , note: "Luca. Pixar Italia. Verano y monstruosidad escondida." },
  { id: 615457 , note: "Nobody. Saulnier-meets-John Wick. Bob Odenkirk inesperado." },
  { id: 12158  , note: "The Curious Case of Benjamin Button. Fincher. Tiempo invertido y tristeza." },
  { id: 5915   , note: "Into the Wild. Penn. Soledad como elección final." },
  { id: 45269  , note: "Searching for Sugar Man. Bendjelloul. Mito musical sudafricano." },
  { id: 87502  , note: "Cartel Land. Heineman. Vigilantes, narcos, sin maquillaje." },
  // ── JOYA INVISIBLE ───────────────────────────────────────────────

  { id: 565743,  note: "Sci-fi retro pequeña y elegante." },
  { id: 453278,  note: "Drama íntimo, físico y silencioso." },
  { id: 428449,  note: "Duelo, tiempo y minimalismo fantasma." },
  { id: 585378,  note: "Sci-fi íntima sobre memoria y familia." },

  // ── CLÁSICO VIVO ─────────────────────────────────────────────────
  { id: 9552,    note: "Friedkin filmó el mal como posibilidad real. Sigue siendo la más perturbadora 50 años después." },
  { id: 207,     note: "Dead Poets Society todavía duele. Weir y Williams en estado de gracia pura." },
  { id: 655,     note: "Distancia, culpa y belleza americana." },
  { id: 797,     note: "Identidad quebrada en blanco y negro." },
  { id: 346,     note: "Kurosawa todavía se siente vivo." },
  { id: 18148,   note: "Familia, tiempo y tristeza contenida." },
  { id: 62,      note: "Sci-fi monumental y todavía moderna." },
  { id: 780,     note: "Rostros, fe y cine puro." },
  { id: 147,     note: "Juventud, libertad y tristeza clásica." },
];

export const CURATED_GROUPS = {
  "oscuro-reflexivo": [965150, 666277, 152601, 466420, 804095, 496243, 491584, 1018, 843, 1398, 68722, 11423],
  "oscuro-tenso": [146233, 49797, 1422, 949, 395834, 27205, 244786, 1949, 473033, 242582, 273481],
  "oscuro-devastador": [807, 9539, 334541, 641, 25237, 12477, 965150, 670, 6977],
  "luz-acompanamiento": [840430, 505600, 122906, 587792, 976893, 370755, 11830, 331482, 505192, 194],
  "luz-adrenalina": [353081, 546554, 515001, 603, 76341, 85, 155, 137113, 361743],
  "frio-contemplativo": [329865, 503919, 254320, 374720, 593, 81401, 414453, 30020],
  "calido-romantico": [531428, 76, 80, 666277, 38, 284],
  "raro-discover": [513434, 220289, 431, 985, 8327, 662, 21484, 25623, 97370, 492],
  "accion-retro": [1103, 106, 562, 5548, 218, 679, 6978],
  "terror-atmosferico": [493922, 310131, 530385, 293670, 27374, 575776, 503919, 694, 805, 36095],
  "comedia-con-alma": [275, 120467, 121986, 773, 115, 8051, 86829],
  "animacion-adulta": [324857, 569094, 10494, 9323, 128, 129, 149, 378064, 10315],
  "documental": [682110, 123678, 128216, 501, 42044, 14275, 30017, 26317],
  "joya-invisible": [565743, 453278, 428449, 585378],
  "clasico-vivo": [9552, 207, 655, 797, 346, 18148, 62, 780, 147],
};

const _byId = new Map(CURATED.map(c => [c.id, c]));
export function curatedFor(tmdbId) {
  return _byId.get(tmdbId) || null;
}

// ────────────────────────────────────────────────────────────────────
// CURATED TV — series picks. Same shape as CURATED, distinct namespace.
// ────────────────────────────────────────────────────────────────────
export const CURATED_TV = [
  // ── PRESTIGE LENTO ───────────────────────────────────────────────
  { id: 1396,  note: "Vince Gilligan filmó la transformación moral más completa de la TV. Cada decisión pesa." },
  { id: 60059, note: "Spinoff que termina superando a la madre. Tragedia legal con paciencia de monje." },
  { id: 95396, note: "Ben Stiller dirige el capitalismo como horror corporativo. Ritmo, diseño y desconcierto." },
  { id: 1399,  note: "Ambición, traición y dragones. Las primeras temporadas siguen siendo TV gigante." },

  // ── MINISERIE DEVASTADORA ────────────────────────────────────────
  { id: 87108, note: "Mazin reconstruyó Chernóbil con precisión documental. Cinco episodios que no se olvidan." },
  { id: 100088, note: "Adaptación rara: respeta el videojuego sin perder cine. El primer episodio te deja mudo." },
  { id: 218230, note: "Shōgun versión 2024. Ambición, poder y silencio japonés filmados con cuidado obsesivo." },

  // ── TENSIÓN / THRILLER ───────────────────────────────────────────
  { id: 46648, note: "True Detective S1: McConaughey y Harrelson en el sur gótico. Resto de temporadas ignorables." },
  { id: 60622, note: "Noah Hawley convierte el universo Coen en serie sin traicionarlo. Cada temporada es nueva." },
  { id: 76479, note: "Sátira ultraviolenta sobre el poder. Funciona porque le importan los personajes." },
  { id: 81356, note: "Squid Game llegó hondo porque el dolor de clase está bien filmado bajo la sangre." },

  // ── HORROR ATMOSFÉRICO TV ────────────────────────────────────────
  { id: 71790, note: "Mike Flanagan filma el duelo como casa que respira. Más triste que aterradora." },
  { id: 60863, note: "Twin Peaks: The Return. Lynch en absoluta libertad. No es para todos, es para nosotros." },

  // ── HORROR / DARK FANTASY TV (expandido QA #4) ──────────────────
  { id: 3470, note: "Antología 2005 con Carpenter, Joe Dante, Tobe Hooper. Cada episodio una película." },
  { id: 1622, note: "Hermanos Winchester en la ruta 66 cazando demonios. Quince temporadas que envejecieron raro." },
  { id: 1405, note: "Asesino con código moral. Procedural retorcido que dura más de lo que aguanta." },
  { id: 7354, note: "Slasher en isla, una víctima por episodio. Trece capítulos exactos." },
  { id: 7087, note: "Vampiro, hombre lobo y fantasma comparten piso en Bristol. Original británica." },
  { id: 10545, note: "Vampiros sureños, sangre sintética y melodrama gótico. Alan Ball." },
  { id: 7831, note: "Reality show post-apocalíptico zombi. Brooker antes de Black Mirror." },
  { id: 14956, note: "Whedon. Cuerpos alquilables, identidades intercambiables. Cancelada justo cuando arrancaba." },
  { id: 39336, note: "Found-footage en el Amazonas. Mockumentary breve y olvidado." },
  { id: 64550, note: "Familia oculta secretos asesinos. Slow-burn de prestige." },
  { id: 46786, note: "Norman Bates antes de Psicosis. Vera Farmiga como madre, claustrofobia familiar." },
  { id: 42295, note: "Hombres lobo y hospitales en pueblo rural de Pennsylvania. Pulp grotesco." },
  { id: 50825, note: "Jinete sin cabeza en el siglo 21. Pulp con humor." },
  { id: 46746, note: "Zombis rehabilitados a la sociedad inglesa. Drama social con monstruos." },
  { id: 40008, note: "Lecter como maestro y musa. Visualmente sigue siendo techo del género." },
  { id: 80055, note: "Trasplante de corazón con espíritu vengativo. Una sola temporada." },
  { id: 85273, note: "Joe Hill. Vampiro psíquico que rapta niños a Christmasland." },
  { id: 65784, note: "Antología canadiense, una temporada un asesino, sin ahorrarse nada." },
  { id: 86423, note: "Llaves mágicas en casa familiar. Fantasía con horror suave." },
  { id: 83631, note: "Vampiros mockumentary en Staten Island. Cómica antes que tenebrosa." },
  { id: 82816, note: "Horror cósmico cruzado con racismo de los 50. Una temporada perfecta." },
  { id: 86848, note: "Investigan milagros y posesiones. Procedural con seriedad teológica inesperada." },
  { id: 88055, note: "Shyamalan produce. Niñera nueva, bebé que no es lo que parece. Casa cerrada." },
  { id: 129418, note: "Hollywood ocultista, gatitos, venganza. Pulp lisérgico." },
  { id: 126118, note: "Stephen King precuela de Salem's Lot. Adrien Brody en Maine." },
  { id: 117488, note: "Fútbol femenino sobrevive accidente aéreo. Caníbales y traumas adultos." },
  { id: 136745, note: "Comedia-horror, escritora se muda a casa con espíritu. Courteney Cox." },
  { id: 112314, note: "Restaurador de cintas descubre culto en los 90. Found-footage moderno." },
  { id: 106651, note: "Yeon Sang-ho. Mensajeros del infierno juzgan en público. Coreana." },
  { id: 99966, note: "Zombis en escuela coreana. Adolescentes encerrados." },
  { id: 135786, note: "Coreana 2024. Maldición e ídolos antiguos." },
  { id: 235851, note: "Documental Apple sobre el caso real británico de 1977." },
  { id: 233629, note: "Cuatro detectives en cuatro épocas, mismo cadáver. Adaptación gráfica." },
  { id: 75191, note: "Antología. Primera temporada: barcos atrapados en hielo, criatura del Ártico." },
  { id: 128839, note: "Sumidero en LA conecta con prehistoria. Pulp catastrofista." },
  { id: 92916, note: "Francesa. Bruja escritora atormenta a su autora. Cancelada con culto inmediato." },
  { id: 46616, note: "Francesa. Muertos vuelven a su pueblo de los Alpes sin saber que murieron." },
  { id: 62097, note: "Sueca. Bosque nórdico, niños desaparecidos, mitología local." },
  { id: 63201, note: "Australiana. Muertos del cementerio reaparecen vivos en pueblo rural." },
  { id: 89844, note: "Española. Iglesias, monedas malditas, pueblo en Segovia. Álex de la Iglesia." },
  { id: 4743, note: "Española. Internado con secretos que llevan décadas. Las mejores series góticas en español." },
  { id: 86621, note: "Sueca. Adolescente acusada de tiroteo. Pulp psicológico nórdico." },
  { id: 71116, note: "Universo Stephen King condensado en pueblo maldito de Maine." },
  { id: 130987, note: "Cronenberg adaptado. Rachel Weisz como gemelas ginecólogas. Body horror corporativo." },
  { id: 98201, note: "Tres veranos, una desaparición, mentiras crecen. Estructura temporal en zigzag." },
  { id: 136738, note: "Comedia romántica con licantropía. Australiana, breve, inesperada." },
  { id: 86686, note: "Antología semanal. Stephen King, fan-service genuino con efectos prácticos." },
  { id: 210232, note: "Familia recibe cartas de un acosador en su casa nueva. Ryan Murphy basado en hechos reales." },
  { id: 70523, note: "Tres generaciones, viajes en el tiempo, Alemania. Pretensión que se sostiene." },
  { id: 67744, note: "Fincher entrevista asesinos seriales reales. Procedural frío con peso ético." },
  { id: 54344, note: "Lindelof. El 2% del mundo desaparece. Duelo cósmico, no respuestas." },
  { id: 60866, note: "Zombi forense come cerebros y resuelve crímenes. CW alegre." },
  { id: 53425, note: "Pueblo en Idaho que oculta algo monstruoso. Twilight Zone moderna." },

  // ── COMEDIA CON ALMA ─────────────────────────────────────────────
  { id: 60625, note: "Rick and Morty cuando funciona es nihilismo cómico de primer nivel." },

  // ── ANIME PRESTIGIO ──────────────────────────────────────────────
  { id: 1429,  note: "Attack on Titan termina cumpliendo la promesa. Política, guerra y trauma sin escapatoria." },
  { id: 95479, note: "Jujutsu Kaisen: animación de combate al nivel más alto del medio." },

  // ── FANTASÍA / SCI-FI ────────────────────────────────────────────
  { id: 66732, note: "Stranger Things temporada 1 y 4. Los Duffer saben cuándo el homenaje funciona." },
  { id: 90802, note: "The Sandman: Gaiman llevado a imagen con respeto y presupuesto. La serie más visual del catálogo." },
  { id: 110316, note: "Alice in Borderland: el mejor survival japonés actual. Tensión sin descanso." },

  // ── ZOMBIE / POSTAPOC ────────────────────────────────────────────
  { id: 1402,  note: "The Walking Dead: las primeras 4 temporadas son TV de género en su mejor momento." },

  // ── PROCEDURAL CON PERSONAJE ─────────────────────────────────────
  { id: 1408,  note: "House M.D.: Hugh Laurie sostiene un procedural médico con química shakesperiana." },

  // ── RAREZA / WTF ─────────────────────────────────────────────────
  { id: 95057, note: "Wednesday funciona porque Jenna Ortega entendió a Burton mejor que el propio Burton." },
  { id: 84958, note: "Loki: la sorpresa de Marvel que se permite ser rara. Owen Wilson como ancla emocional." },
  // ── MÁS SERIES (prestige / comedy / weird) ─────────────────────
  { id: 1438   , note: "The Wire. Simon hizo cinco temporadas de tesis sociológica disfrazada de policial. La cumbre del medio." },
  { id: 1437   , note: "Deadwood. Milch escribió Shakespeare con groserías. Diálogo como arte." },
  { id: 76331  , note: "Succession. Drama familiar con mejor diálogo que cualquier obra teatral del siglo." },
  { id: 61222  , note: "BoJack Horseman. La animación más triste y honesta sobre depresión y autodestrucción." },
  { id: 30991  , note: "Cowboy Bebop. Watanabe inventó el jazz space-noir. Sigue siendo el techo del anime adulto." },
  { id: 13916  , note: "Death Note. El cat-and-mouse más adictivo del medio." },
  { id: 67915  , note: "Atlanta. Glover hace que cada episodio sea una película distinta. Surrealismo y peso de raza." },
  { id: 60875  , note: "Fleabag temporada 2. Phoebe Waller-Bridge convirtió la cuarta pared en arma." },
  { id: 97546  , note: "Reservation Dogs. Sterlin Harjo filmó adolescencia indígena con ternura y humor seco." },
  { id: 90400  , note: "I May Destroy You. Coel escribe trauma como comedia incómoda. Sin red de seguridad." },
  { id: 87739  , note: "The Queen's Gambit. Ajedrez como drama interno. Anya Taylor-Joy lleva todo." },
  { id: 95011  , note: "WandaVision. Marvel cuando se permite duelo y experimentación formal." },
  { id: 1668   , note: "Friends. Conducta social de los 90 fosilizada. Funciona porque el cast químico es real." },
  { id: 1100   , note: "How I Met Your Mother. Pegada cómica fuerte hasta que el final se desinfló." },
  { id: 212808 , note: "The Bear. Carmy en cocina como purgatorio existencial. Ritmo de pulso." },
  { id: 114695 , note: "Andor. Star Wars hecho thriller adulto. Gilroy escribe revolución sin caricatura." },
  { id: 94605  , note: "Arcane. Animación que reinventa el biopic de superhéroe. League of Legends sin parecerlo." },
  { id: 138502 , note: "Mr. & Mrs. Smith. Donald Glover y Maya Erskine como espías casados. Comedy + thriller." },

  // ── EXTRAS · más series ─────────────────────────────────────
  { id: 62286  , note: "Mr. Robot. Esmail. Paranoia digital y tipografía neurótica." },
  { id: 70523  , note: "Dark. Friese. Pueblo alemán, túnel temporal y ciencia narrativa apretada." },
  { id: 1606   , note: "American Horror Story. Murphy excesivo, antología desigual pero memorable." },
  { id: 67419  , note: "The Haunting of Hill House. Flanagan. Casa como duelo familiar." },
  { id: 113962 , note: "Midnight Mass. Flanagan. Iglesia, fe y vampiros sin nombrarlos." },
  { id: 456    , note: "The Simpsons (clásica). Temporadas 3-9 son canon comedia americana." },
  { id: 615    , note: "Futurama. Groening en sci-fi blanda y emotiva." },
  { id: 62127  , note: "Atypical. Comedia familiar sobre autismo. Liviana pero con corazón." },
  { id: 94997  , note: "House of the Dragon. Game of Thrones precuela, dragones y crisis sucesoria." },


  // ── EXTRAS · expansión catálogo TV ─────────────────────────
  { id: 1398    , note: "The Sopranos. Chase escribió el padre del prestige drama. Tony Soprano sigue siendo el personaje más complejo de la TV." },
  { id: 1418    , note: "The Big Bang Theory. Sitcom mainstream que decae pero los primeros años funcionan como comedia confort." },
  { id: 4614    , note: "NYPD Blue. Bochco y Milch redefinieron el procedural policial en los 90s. Sciorra al frente." },
  { id: 1416    , note: "Grey's Anatomy. Rhimes inventó el drama médico moderno. Vio mejor en sus primeras seis temporadas." },
  { id: 1622    , note: "Supernatural. Hermanos Winchester como folclor americano. Las primeras cinco son canon." },
  { id: 60572   , note: "The Knick. Soderbergh dirige medicina del 1900 como horror corporal. Olvidada injustamente." },
  { id: 87917   , note: "The Underground Railroad. Barry Jenkins filma el dolor con dignidad poética imposible." },
  { id: 94954   , note: "Hacks. Jean Smart como comediante en decadencia. Ritmo y química perfectos." },
  { id: 110492  , note: "Peacemaker. James Gunn divirtiéndose como nadie en TV de superhéroes." },
  { id: 135138  , note: "Slow Horses. Gary Oldman en MI5 como espía caído. Una sorpresa por temporada." },
  { id: 124364  , note: "From. Pueblo donde no se puede salir. Misterio sin fin pero te atrapa." },
  { id: 152040  , note: "Beef. Lee Sung Jin convierte road rage en arqueología emocional. Wong y Yeun en la cumbre." },
  { id: 105248  , note: "Cobra Kai. Karate Kid 30 años después como dramedy adolescente. Funciona mejor de lo que debería." },
  { id: 114472  , note: "The Last of Us. Mazin adaptó el videojuego sin perder cine. Episodio 3 es televisión seminal." },
  { id: 61888   , note: "Master of None. Aziz Ansari y Alan Yang. Episodios sueltos como cortos perfectos." },
  { id: 84773   , note: "Ted Lasso. Sudeikis como entrenador yanqui en Inglaterra. Optimismo sin azúcar." },
  { id: 138670  , note: "Tokyo Vice. Periodismo y yakuza en los 90. Adam Wingard al ritmo." },
  { id: 71712   , note: "Babylon Berlin. Berlín 1929 filmado como ciudad enferma. Producción europea más grande de la historia." },
  { id: 153312  , note: "Severance. Stiller dirige el capitalismo como horror corporativo. Ritmo, diseño y desconcierto." },
  { id: 153406  , note: "The Bear. Cocina de Chicago como purgatorio. Episodio Fishes es televisión seminal." },
  { id: 104389  , note: "Yellowjackets. Adolescencia + canibalismo + 90s. Ritmo deliberado, recompensa lenta." },
  { id: 203857  , note: "Shrinking. Bill Lawrence + Jason Segel. Comedia sobre duelo sin ser empalagosa." },
  { id: 114502  , note: "The Bear. Carmy. Fuegos. Ya está dicho." },
  { id: 220937  , note: "The Curse. Nathan Fielder en bucle de incomodidad sostenida. No para todos." },
  { id: 215103  , note: "Poker Face. Rian Johnson + Natasha Lyonne. Howdunit semanal con química perfecta." },


  // ── EXTRAS · series del taste del autor (Trakt) ────────────
  { id: 1973    , note: "24. Kiefer Sutherland en tiempo real. Tensión sostenida que define la tele post-9/11. Las primeras 5 temporadas son canon." },
  { id: 48891   , note: "Brooklyn Nine-Nine. Schur entiende que la sitcom workplace funciona cuando el cast se quiere de verdad. Andy Samberg sin sobre-actuar." },
  { id: 4087    , note: "The X-Files. Mulder y Scully inventaron la dinámica creyente/escéptico que copió la TV entera. Episodios MOTW siguen siendo top." },
  { id: 2316    , note: "The Office (US). Greg Daniels traduce Gervais sin traicionarlo. Temporadas 2-5 son comedia documental perfecta." },
  { id: 37680   , note: "Suits. Procedural legal con química Harvey/Mike. Mejor cuando se enfoca en casos, peor cuando recae en romance." },
  { id: 34307   , note: "Shameless (US). Familia Gallagher como crónica de pobreza en Chicago. Macy y Rossum sostienen el caos." },
  { id: 1403    , note: "Agents of S.H.I.E.L.D. Marvel TV antes de Disney+. Coulson como ancla. Mejora drásticamente desde S2." },
  { id: 1420    , note: "New Girl. Liz Meriwether escribe amistad adulta como comedia física. Schmidt es uno de los mejores personajes secundarios de la TV." },
  { id: 4607    , note: "Lost. Lindelof y Cuse construyeron el misterio más grande de los 2000s. El final divide pero el viaje es televisión seminal." },
  { id: 79744   , note: "The Rookie. Procedural policial liviano con Nathan Fillion. Sin pretensiones, episodios autocontenidos." },
  { id: 60797   , note: "Scorpion. Procedural de genios. Liviano, formulaico, perfecto para fondo." },
  { id: 1412    , note: "Arrow. CW oscuro que lanzó el Arrowverse. Las primeras 3 temporadas son lo mejor del DC TV." },
  { id: 1411    , note: "Person of Interest. Nolan hermano hace sci-fi paranoide disfrazada de procedural. La sorpresa de la década." },
  { id: 18347   , note: "Community. Dan Harmon escribe meta-comedy académica. Cada temporada cambia de género. Tropes y absurdo en niveles raros." },
  { id: 1407    , note: "Homeland. Mandy Patinkin y Claire Danes en thriller geopolítico. Temporadas 1-4 son tensión sostenida." },
  { id: 1405    , note: "Dexter. Forense asesino. Temporadas 1, 2 y 4 son canónicas. Después decae fuerte hasta resucitar con New Blood." },
  { id: 1409    , note: "Sons of Anarchy. Sutter hace Hamlet con motos. Charlie Hunnam y Katey Sagal sostienen la tragedia." },
  { id: 44217   , note: "Vikings. Hirst convierte saga nórdica en TV operática. Travis Fimmel como Ragnar es magnético." },
  { id: 46952   , note: "The Blacklist. James Spader devorando escenas como Reddington. Procedural inflado pero entretenido." },
  { id: 1705    , note: "Fringe. JJ Abrams hace X-Files con física cuántica. Anna Torv merecía más reconocimiento." },
  { id: 1424    , note: "Orange Is the New Black. Kohan hizo TV coral sobre prisión femenina. Cada personaje tiene mundo." },
  { id: 2046    , note: "Alias. JJ Abrams pre-Lost. Jennifer Garner como espía adulta. Mejor que se recuerda." },
  { id: 61418   , note: "Jane the Virgin. Telenovela meta con narrador que sabe. Gina Rodriguez es químicamente perfecta." },
  { id: 2288    , note: "Prison Break. Premisa simple, ejecución obsesiva. Las primeras dos temporadas son TV de pulso." },
  { id: 46533   , note: "The Americans. Espías rusos en suburbios americanos. Una de las mejores series jamás vistas, sin que casi nadie hablara." },
  { id: 4589    , note: "Arrested Development. Hurwitz inventó la sitcom que se relee. Densidad de bromas más alta del medio." },
  { id: 10545   , note: "True Blood. Alan Ball convierte vampiros sureños en pulp queer. Temporadas 1-3 son lo mejor." },
  { id: 31295   , note: "Misfits. Jóvenes con superpoderes en Inglaterra. Crudo, gracioso, británico. Las primeras dos temporadas son perfectas." },
  { id: 21510   , note: "White Collar. Caper liviano con Matt Bomer. Ritmo suave para fondo." },
  { id: 61056   , note: "How to Get Away with Murder. Shonda Rhimes en modo thriller. Viola Davis devora cada escena." },
  { id: 60573   , note: "Silicon Valley. Mike Judge satirizando startup culture. Comedia tech más certera jamás filmada." },
  { id: 1425    , note: "House of Cards. Fincher dirige el piloto. Spacey aparte, las primeras 3 temporadas son thriller político de alta gama." },
  { id: 1410    , note: "Revolution. Apocalipsis sin electricidad. Premisa fuerte, ejecución desigual." },
  { id: 63174   , note: "Lucifer. Tom Ellis encarnando al diablo como detective. Procedural liviano con química." },
  { id: 60802   , note: "The Last Ship. Naval post-apocalíptico. Producción militar con escala cinematográfica." },
  { id: 60735   , note: "The Flash. CW Arrowverse en modo soleado. Mejor cuando hace ciencia ficción que cuando hace soap." },
  { id: 61463   , note: "The Affair. Sarah Treem hace drama Rashomon de pareja. Ruth Wilson y Dominic West en la cumbre." },
  { id: 62560   , note: "Mr. Robot. Sam Esmail. Paranoia digital y tipografía neurótica." },
  { id: 46786   , note: "Bates Motel. Precuela de Psycho como drama familiar. Vera Farmiga y Freddie Highmore inventan tensión." },
  { id: 45094   , note: "The Following. Kevin Williamson en modo thriller. Bacon y Purefoy juegan al gato y ratón." },
  { id: 41727   , note: "Banshee. Pulpa de acción seria. Cinemax cuando hacía TV de género bien." },
  { id: 66573   , note: "The Good Place. Mike Schur reescribe la sitcom como filosofía moral. Final perfecto en cuatro temporadas." },
  { id: 86848   , note: "Evil. Procedural de exorcismo con humor. Katja Herbers y Mike Colter como duo escéptico/creyente." },
  { id: 124101  , note: "Hacks. Jean Smart como comediante en decadencia. Ritmo y química perfectos." },
  { id: 61889   , note: "Marvel's Daredevil. Drew Goddard hizo el mejor MCU TV. Coreografía de pasillo es referencia obligada." },
  { id: 34415   , note: "The Killing. Veena Sud hace whodunit lluvioso en Seattle. Mireille Enos como detective fundamental." },
  { id: 67166   , note: "El Marginal. Cárcel argentina como microcosmos. Acción, drama y producción local de alto nivel." },
  { id: 71446   , note: "Money Heist. Spanish heist como pop event global. Las primeras dos temporadas son ritmo puro." },
  { id: 61664   , note: "Sense8. Wachowskis hacen TV utópica sobre conexión humana. Visualmente única, emocionalmente honesta." },
  { id: 63351   , note: "Narcos. Pablo Escobar como drama internacional. Wagner Moura es magnético." },
  { id: 66857   , note: "Shooter. Mark Wahlberg francotirador. Procedural militar funcional." },
  { id: 46296   , note: "Spartacus. Sangre, sexo y mármol. La temporada Vengeance es genuinamente buena bajo todo el slow-mo." },
  { id: 211288  , note: "Tracker. Justin Hartley como rastreador. Procedural reciente con buen ritmo." },
  { id: 71578   , note: "Atypical. Comedia familiar sobre autismo. Liviana pero con corazón." },
  { id: 66788   , note: "13 Reasons Why. Polémica calculada. Primera temporada funciona como adaptación, después se infla." },
  { id: 34967   , note: "Falling Skies. Steven Spielberg produce alienígenas post-invasión. Familiar y funcional." },
  { id: 73107   , note: "Barry. Bill Hader convierte sicario en clase de actuación. Comedia negra absoluta." },
  { id: 67026   , note: "Designated Survivor. Kiefer Sutherland como presidente accidental. Thriller político decente." },
  { id: 42009   , note: "Black Mirror. Charlie Brooker antología tecnológica. Episodios USS Callister, San Junipero, White Bear son canon." },

];

const _tvById = new Map(CURATED_TV.map(c => [c.id, c]));
export function curatedTvFor(tmdbId) {
  return _tvById.get(tmdbId) || null;
}
